### ISSUE TITLE
Is it possible to package themes separately?

### ISSUE THREAD

**Issue by markusgod** [lassekongo83/adw-colors#10]
I'm using extension Night Theme Switcher and to work it requires separate "theme packages".
![image](https://user-images.githubusercontent.com/20001291/183353557-72a10aac-10f8-4e80-8b4f-1840d8efca2e.png)
I'm not sure how to achieve this with this kind of base theme augmentation.

**Comment by lassekongo83** [comment]
XDG_CONFIG_HOME/gtk-3.0 or 4.0 can only read one gtk.css file. It's either light or dark, can't be both unfortunately. I'd rather not maintain complete separate themes.
