### ISSUE TITLE
Color theme request: Cobalt

### ISSUE THREAD

**Issue by user1-github** [lassekongo83/adw-colors#16]
It would be appreciated if someone could make a Cobalt color theme, like the one that is used in Gnome Text Editor:

![Cobalt](https://user-images.githubusercontent.com/56021366/190683407-f0ab2457-3364-480f-95e0-3413e8fd913e.png)

**Comment by lassekongo83** [comment]
The [Gradience](https://github.com/GradienceTeam/Gradience) project have a Cobalt preset. https://github.com/GradienceTeam/Community/blob/next/official/cobalt-dark.json
