### ISSUE TITLE
Cant apply on Arch Linux

### ISSUE THREAD

**Issue by ghost** [lassekongo83/adw-colors#18]
I dowmloaded alpha-mac gtk.css, put it ond ~/.config/gtk-4.0/ folder and when i try to aplly nothing apears. 
When try to open gtk.css file from gnome-tweaks it doesnt see the file on the folder. Please help me

**Comment by lassekongo83** [comment]
gnome-tweaks is not used. Just follow all steps: https://github.com/lassekongo83/adw-colors#how-to-install (especially step 5).
