### ISSUE TITLE
Original gtk.css

### ISSUE THREAD

**Issue by Raubion** [lassekongo83/adw-colors#2]
Hey, thanks so much for your work on the adw theme and now also providing the possibility of variants in color. 

I want to play around a bit with the color schemes, and was wondering if you could also list the 'regular' libadwaita gtk.css under available themes. This would give me (and perhaps others) the opportunity to compare a bit between the original theme and the new variants. For instance: I prefer the regular libadwaita close, minimize and maximize buttons. But I can't figure out how to get those back in the peninsula variant. 

Another variant of this suggestion is a more detailed 'how to' with not only the listed supported name colors but also screenshots of each of the categories.

**Comment by lassekongo83** [comment]
The original libadwaita theme can be found here: https://gitlab.gnome.org/GNOME/libadwaita/-/tree/main/src/stylesheet

So for the window control buttons: https://gitlab.gnome.org/GNOME/libadwaita/-/blob/main/src/stylesheet/widgets/_header-bar.scss#L93 (Simply remove all `windowcontrol > button ...`)

**Comment by Raubion** [comment]
Thanks for your quick reply. Previously I deleted the windowcontrol parts of your code and it worked for GTK4 but it somehow produced a lot of white spots for gtk3. However, I just did it again and now it works, so that's great.
