### ISSUE TITLE
Have you considered porting all themes to Gradience?

### ISSUE THREAD

**Issue by Arcitec** [lassekongo83/adw-colors#22]
Hi Lasse, I'm a fellow Swede, hoppas du har en fin fika! :)

Gradience has emerged as the primary way to re-color the GNOME desktop. It's getting support for Shell themes and even GDM login themes. And it has a growing repository of custom themes. It's also made specifically to work with adw-gtk3.

All gtk.css features are supported in its theme files, such as defining colors to refer to other colors (ie `@window_bg_color`), and adding custom built-in CSS to the themes.

It also has great benefits, such as being able to apply any theme *AND* your own custom user CSS overrides. So for example, I use the following Tilix CSS override in gtk-3.0's CSS file, to get nicer padding around the terminal windows, which Gradience can automatically insert into all Adwaita color themes for me:

```css
.tilix-background vte-terminal {
  padding: 10px;
}
```

Adding such custom CSS is a real pain when cloning the latest versions of themes from the `adw-colors` repo instead, since they overwrite the entire CSS file.

That's making this separate theme repository look really unappealing compared to Gradience's excellent (and growing) feature set.

So the question is... are there any thoughts about gradually porting themes to Gradience instead, and deprecating this repo, so that GNOME lovers have a more advanced way to install themes? :D

Just a thought. Totally fine if you don't think Gradience is a good application. It looks like it's the future of GNOME theming though.

**Comment by lassekongo83** [comment]
Maybe/maybe not. I prefer to write everything by hand personally.

**Comment by Bananaman** [comment]
> Maybe/maybe not. I prefer to write everything by hand personally.

Yeah. I was personally against Gradience until recently, but it has far surpassed my expectations of the project. It solves a lot of issues with GNOME theming, in a consistent way, ensuring that CSS is valid, installed in proper files, and that user-CSS is preserved. Everything you did by hand here is doable in Gradience themes too, with `@color` references and custom CSS.

And when 0.8.0 is out with Shell and GDM theme support I think it'll be the final nail in the coffin that cements it as the best way to theme GNOME. Then it will be possible to add shell colors for all custom themes. That's gonna be a game-changer. :D

Considering that we're all using GNOME already, it shouldn't be a crime to use a 1-click GUI for theming btw. ;)

**Comment by Arcitec** [comment]
Hi @lassekongo83, I spoke to [Daudix and 0xMRTT](https://github.com/GradienceTeam/Gradience/graphs/contributors) today on [Matrix](https://matrix.to/#/#Gradience:matrix.org). I can highly recommend checking out that place.

There's ideas about most likely adding a new URL handler so that themes can be installed directly via your repo, with Gradience. This is their badge for that purpose:

![Gradience Banner](https://raw.githubusercontent.com/GradienceTeam/Design/main/Badges/download-i.svg)

The URL handler would look something like `gradience://raw/https://github.com/lassekongo83/adw-colors/tree/main/themes/dracula/dracula.json`

There's of course no guarantee or promise, but 0xMRTT said "i'll make a url for redirecting to the theme from the badge" so it really sounds like it'll be added.

I think that sounds like a great idea since it would let creators keep Git control of themes while still having a better way of installing the themes. :)

Oh and also... Glad Sommar, it's finally here-ish in Sweden. :D

**Comment by lassekongo83** [comment]
I can see some problems with this suggestion. I write my themes in sass to make it more manageable with a lot of custom CSS. I also use some custom image assets which I don't believe Gradience support. (Correct me if I'm wrong). It would also need to grab an assets folder for it to work.

**Comment by keilmillerjr** [comment]
Gradience is a neat idea. However, it is riddled with bugs and lacking in support. I hope this changes. However, the issues with gradience lead me to adw-colors. I like the simplicity of adding/swapping a single file to change a theme. I don't need a gui and the ability to change the color of every single individual element. Perhaps I can help contribute in a way to make this process even easier.

**Comment by lassekongo83** [comment]
Gradience is no longer maintained.

**Comment by Arcitec** [comment]
Yeah, now we know what happened. The main developer silently left and was away for almost a year, until the app died. It's sad. With a bit more features (especially image assets for themes) it could have been "the" app for everyone.
