### ISSUE TITLE
doesn't work on fedora.

### ISSUE THREAD

**Issue by CodedIsTaken** [lassekongo83/adw-colors#26]
llah-egas@hp-laptop-15-dy5xxx:~/Downloads$ sh accent-color-change.sh
This program will overwrite (but create backups) of the config files ~/.config/gtk-3.0/gtk.css and ~/.config/gtk-4.0/gtk.css if they exist. Are you sure you want to proceed?
Proceed? (y/n) yContinuing...
Package gtk4 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk4.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gtk4' not found
Error: GTK4 is not installed or not found in PATH.
llah-egas@hp-laptop-15-dy5xxx:~/Downloads$

**Comment by lassekongo83** [comment]
Try the new version of the script.

**Comment by CodedIsTaken** [comment]
Ok

**Comment by CodedIsTaken** [comment]
Thanks
