### ISSUE TITLE
Hot Reloading Colors in ~/.config/gtk-3.0/gtk.css?

### ISSUE THREAD

**Issue by mewoocat** [lassekongo83/adw-colors#29]
Is there a feasible way to hot reload the user's `~/.config/gtk-3.0/gtk.css` file so that restarting the apps is not required?  I thought that resetting the gtk theme with gsettings might trigger a reload but it doesn't appear to be the case.  If there really isn't a reasonable way to accomplish, this feel free to just close the issue.  Thanks

**Comment by lassekongo83** [comment]
Not possible.
