### ISSUE TITLE
Creating light theme with dark headerbar (adwaita-darker)

### ISSUE THREAD

**Issue by robrobinbin** [lassekongo83/adw-colors#4]
Hi there,

I'm trying to create a theme where the header/titlebar is dark, but the rest is light.

So far I have the following:
```CSS
@define-color headerbar_bg_color #303030;
@define-color headerbar_fg_color white;
@define-color headerbar_backdrop_color #242424;
```
This works fairly well for GTK4 apps (with the exception of some less nice edges in the top corners)
![image](https://user-images.githubusercontent.com/8597693/177369635-45f982b2-a825-4e0f-8eb1-99482d1884c1.png)

But it's not working well for GTK3 applications (using adw-gtk3). 
It looks okay when the window is unfocused:

![image](https://user-images.githubusercontent.com/8597693/177370024-167dfced-bfc6-4f26-b73e-a7d745bf529b.png)

But when focused, most elements are illegible
![image](https://user-images.githubusercontent.com/8597693/177370080-7a568ade-b671-4578-a6bd-b7d39697482e.png)

**Comment by robrobinbin** [comment]
I did some investigating and it appears that adw-gtk3 is using `window_fg_color` for those illegible elements, rather than `headerbar_fg_color`.

I had a short look at the adw-gtk3 code, but didn't manage to figure out yet where to fix this.

**Comment by robrobinbin** [comment]
Thanks for the quick response!

I found two related bugs:
One with Firefox:
![image](https://user-images.githubusercontent.com/8597693/177388850-990269dc-1afe-4dc3-a4b9-c4f3ec2b62e2.png)

And the other one with unfocused Nautilus:
![image](https://user-images.githubusercontent.com/8597693/177389018-9c2e9167-c26e-4177-a4b8-020143d9b0d1.png)

Let me know if you prefer me to make a new issue for this (in adw-gtk)

**Comment by lassekongo83** [comment]
Forgot to add `headerbar_backdrop_color` to that button in nautilus.

As for Firefox, try a relog as I couldn't reproduce.

**Comment by robrobinbin** [comment]
Thanks again!

> As for Firefox, try a relog as I couldn't reproduce.

I just realized this is probably because I'm using the flatpak version of firefox, so it might not be sourcing the theme with the latest changes from ~/.local/share/themes

**Comment by lassekongo83** [comment]
Found an ugly hack to get the rounded corner bleed to go away.

```css
window > contents {
  background-image: linear-gradient(to bottom, black 12px, $window_bg_color 12px);
}
```

I haven't tested it enough. Some apps with no headerbars may look even uglier.

**Comment by mz1193** [comment]
I've had some luck adding something like this:

`window {
  outline-color: #000000;
  outline-width: 1.1px;
}`

It doesn't really remove the problem so much as the new border masks what's going on in the corners. Keep in mind that a consequence of this code is that you'll also have borders around all GTK4 windows. Personally I like those, but you may not.

Hope this helps!
