### ISSUE TITLE
How to revert to adw-gtk or undo adw-colors

### ISSUE THREAD

**Issue by ajay230ps** [lassekongo83/adw-colors#5]
Hi,

I used the adw-colors using the tutorial, it worked perfectly.

But if I want to go back to the original adw-gtk theme, how can I do that. My understanding is that if I delete the file [~/.config/gtk-4.0/gtk.css] and remove the symlink it should go back to original.

So if I run the same below command will it revert for Flatpak app too ? 

sudo flatpak override --filesystem=xdg-config/gtk-3.0 && sudo flatpak override --filesystem=xdg-config/gtk-4.0

Please let me know if my understanding is correct.

Also please share the adw-colors for light theme if possible.

**Comment by lassekongo83** [comment]
Just remove `~/.config/gtk-4.0/gtk.css` and `~/.config/gtk-3.0/gtk.css`. No other steps needed.
